name: build-test

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++
      - name: Compilation
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          
      - name: Upload generated executables
        uses: actions/upload-artifact@v4
        with:
          name: robot-command-executable
          path: build/robot_cmd_sequene
          retention-days: 7
